name: Nuclei Scanning for Exposed-Panels Templates

on:
  repository_dispatch:
    types: [trigger_nuclei]

jobs:
  nuclei_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout recon-automation Results
        uses: actions/checkout@v3
        with:
          repository: Pcoder7/recon-automation
          ref: main
          path: .  # Check out into the root so "results" is available directly
          # If recon-automation were private, add: token: ${{ secrets.PAT_TOKEN }}

      - name: Update & Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl git unzip
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Adjust as needed

      - name: Install nuclei
        run: |
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          nuclei -ut

      - name: Run Nuclei Scanning on Recon Results
        run: |
          mkdir -p nuclei_results
          # Loop through each domain directory under results
          for domain_dir in results/*; do
            domain=$(basename "$domain_dir")
            echo "Scanning $domain with nuclei for exposed-panels templates"
            if [ -f "$domain_dir/all_resolved.txt" ]; then
              cat "$domain_dir/all_httpx.txt" | awk -F'[ \t]+' '{print $1}' | nuclei -t ~/nuclei-templates/http/exposed-panels -t ~/nuclei-templates/http/default_logins -no-color -o "$domain".txt
            else
              echo "combined.txt not found for $domain"
            fi
          done

      - name: Upload Nuclei Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results
          path: nuclei_results/
